# Generated by Django 6.0.2 on 2026-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project_topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
