# Generated by Django 6.0.2 on 2026-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_task_day_report_task_project_topic_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='reporting_officer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
