# Generated by Django 6.0.2 on 2026-02-18 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_staff_additional_details_staff_reporting_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_topic', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('report_text', models.TextField(blank=True)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='daily_updates', to='adminpanel.task')),
            ],
            options={
                'ordering': ['report_date', 'id'],
            },
        ),
    ]
