# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion


def forwards_create_projects_from_task_topic(apps, schema_editor):
    Project = apps.get_model('adminpanel', 'Project')
    Task = apps.get_model('adminpanel', 'Task')

    project_cache = {}
    for task in Task.objects.exclude(project_topic='').iterator():
        project_name = task.project_topic.strip()
        if not project_name:
            continue
        project = project_cache.get(project_name)
        if project is None:
            project, _ = Project.objects.get_or_create(name=project_name)
            project_cache[project_name] = project
        task.project_id = project.id
        task.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_taskdailyupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Planned', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='adminpanel.project'),
        ),
        migrations.RunPython(forwards_create_projects_from_task_topic, migrations.RunPython.noop),
    ]
