# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='availability_status',
            field=models.CharField(
                choices=[('Available', 'Available'), ('On Leave', 'On Leave'), ('Unavailable', 'Unavailable')],
                default='Available',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='staff',
            name='leave_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
