# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_taskactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Project Management', max_length=150)),
                ('working_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=100)),
                ('reminder_time', models.TimeField(default='09:00')),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
