# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
