# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_staff_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reminders', models.BooleanField(default=True)),
                ('in_app_reminders', models.BooleanField(default=True)),
                ('due_tomorrow_enabled', models.BooleanField(default=True)),
                ('overdue_enabled', models.BooleanField(default=True)),
                ('mention_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to='adminpanel.staff')),
            ],
        ),
    ]
